-- 코드를 작성해주세요
WITH G AS (SELECT ID, BIN(GENOTYPE) AS BINO FROM ECOLI_DATA )

SELECT COUNT(*) AS COUNT FROM ECOLI_DATA AS E LEFT JOIN G ON E.ID = G.ID
WHERE (BINO LIKE '%101') OR (BINO LIKE '%01') OR (BINO LIKE '%100') OR (BINO LIKE '1')
;


