-- 코드를 작성해주세요
SELECT D.ID, IFNULL(C.C_COUNT,0) CHILD_COUNT FROM ECOLI_DATA AS D
LEFT JOIN (SELECT PARENT_ID, COUNT(PARENT_ID) AS C_COUNT
           FROM ECOLI_DATA
            GROUP BY PARENT_ID) AS C 
    ON D.ID = C.PARENT_ID