-- 코드를 작성해주세요
WITH SIZE AS 
(SELECT ID, 
        SIZE_OF_COLONY, 
        YEAR(DIFFERENTIATION_DATE) AS YEAR
FROM ECOLI_DATA)

SELECT S.YEAR, MAX_SIZE - SIZE_OF_COLONY AS YEAR_DEV, ID
FROM SIZE AS S
LEFT JOIN 
(SELECT 
 YEAR(DIFFERENTIATION_DATE) AS YEAR, 
 MAX(SIZE_OF_COLONY) AS MAX_SIZE FROM ECOLI_DATA
 GROUP BY YEAR(DIFFERENTIATION_DATE)
) AS D
 ON S.YEAR = D.YEAR
 ORDER BY YEAR, YEAR_DEV;