-- 코드를 입력하세요
SELECT  P.PRODUCT_CODE, P.PRICE * SUM(O.SALES_AMOUNT) AS SALES
FROM OFFLINE_SALE AS  O LEFT OUTER JOIN PRODUCT AS P 
ON O.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY 2 DESC, P.PRODUCT_CODE;
