-- 코드를 작성해주세요 분기를 나누는 쿼터가 있나?3/6/9/12
SELECT CASE 
        WHEN MONTH(DATE(DIFFERENTIATION_DATE)) <= 3 THEN '1Q'
        WHEN MONTH(DATE(DIFFERENTIATION_DATE)) <= 6 THEN '2Q'
        WHEN MONTH(DATE(DIFFERENTIATION_DATE)) <= 9 THEN '3Q'
        ELSE '4Q'
        END AS QUARTER, COUNT(ID) AS ECOLI_COUNT
FROM ECOLI_DATA
GROUP BY QUARTER
ORDER BY QUARTER